
version: 2

models:
    - name: src_listings
      description: "A starter dbt model"
      columns:
          - name: listing_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: src_reviews
      description: "A starter dbt model"
      columns:
          - name: listing_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
